### ISSUE TITLE
CW37 TODO

### ISSUE THREAD

**Issue by chloe4E** [chloe4E/glamgrab#35]
- what?

- [ ] display full product image on homePage Product Card
- [ ] create a PDP
- [ ] finalize productReivewCard with total  and a delete button
- [ ] BagReviewPage: add proceed to payment button
- [ ] HomePage: Add a filter by category (navigation tbc)

- why?
  
- how?
